server:
  port: 6060
spring:
  cloud:
    server:
      git:
        default-label: config-server
        uri: https://github.com/lmar11xd/prueba-ms-omni
        search-paths: config-data
        clone-on-start: true
application:
  name: config-service